# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_auto_20160522_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='original_release_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='resource_type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
