# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_auto_20160522_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='aliases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
